### ISSUE TITLE
PHP 7 compatibility?

### ISSUE THREAD

**Issue by zag2me** [craigrodway/logintracker#1]
Before I start writing my own script I was wondering if there was any chance of upgrading this to PHP7?

PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in C:\inetpub\wwwroot\logintracker\include\database.class.php:77
Stack trace:
#0 C:\inetpub\wwwroot\logintracker\include\head.php(14): Database->connect()
#1 C:\inetpub\wwwroot\logintracker\index.php(2): require('C:\\inetpub\\wwwr...')
#2 {main}
  thrown in C:\inetpub\wwwroot\logintracker\include\database.class.php on line 77

I'm guessing it needs mysqli support.

**Comment by zag2me** [comment]
ping @craigrodway
